dist: trusty
language: python
cache: pip
python:
  - 3.6
sudo: false
install:
  - pip install codespell flake8 ipyvolume matplotlib mne numpy nibabel pydocstyle scipy
script:
  - make pep
  - python -c "import mne_g3d"  # just a smoke test for now
