dist: trusty
language: python
cache: pip
python:
  - 3.6
sudo: false
install:
  - pip install codespell flake8 ipyvolume matplotlib mne numpy nibabel pydocstyle pythreejs scipy bqplot pytest
script:
  - make pep
  - pytest # unit tests
  - python -c "import ipysurfer"  # a smoke test
