dist: trusty
language: python
cache: pip
python:
  - 3.6
sudo: false
install:
  - pip install codespell flake8 pydocstyle pytest pytest-cov
  - python setup.py install
script:
  - make pep
  - pytest # unit tests
  - python -c "import ipysurfer"  # a smoke test
