dist: trusty
language: python
cache: pip
python:
  - 3.6
sudo: false
install:
  - pip install codespell flake8 pydocstyle
  - python setup.py install
script:
  - make pep
  - python -c "import mne_g3d"  # just a smoke test for now
